{{- if and .Values.jellyfin.enabled .Values.jellyfin.tailscale.enabled (eq .Values.jellyfin.tailscale.mode "sidecar") }}
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth-secret
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
type: Opaque
data:
    TS_AUTHKEY: {{ .Values.jellyfin.tailscale.sidecar.authKey | b64enc }}
{{- end }}
