{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  AUTH_KEY: {{ required "The AUTH_KEY value is missing." .Values.secret.authKey }}
  NAME: {{ required "The NAME value is missing." .Values.secret.dnsRecord }}
  RECORD_ID: {{ required "The RECORD_ID value is missing." .Values.secret.recordId }}
  ZONE_ID: {{ required "The ZONE_ID value is missing." .Values.secret.zoneId }}
{{- end }}
