name: traefik-whitelist-ddns
maintainers:
  - name: kubitodev
    url: https://kubito.dev
apiVersion: v2
appVersion: 2.8.0
version: 1.0.0
description: Kubito Traefik Whitelist DDNS Helm Chart
home: https://github.com/kubitodev/helm/charts/traefik-whitelist-ddns
icon: https://kubito.dev/images/kubito.svg
keywords:
  - kubernetes
  - traefik
  - ddns
  - cronjob
  - middleware
  - ip
  - whitelist
sources:
  - https://github.com/kubitodev/traefik-whitelist-ddns
