apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.middleware.name }}
  namespace: {{ .Release.Namespace }}
spec:
  plugin:
    cloudflared-source-ip:
      excludednets:
        - {{ .Values.middleware.excludedNets }}
