{{- if not .Values.traefik.cloudflareTls.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  tls.crt: {{ required "The tls.crt value is missing." .Values.traefik.cloudflareTls.crt | b64enc }}
  tls.key: {{ required "The tls.key value is missing." .Values.traefik.cloudflareTls.key | b64enc }}
{{- end }}
