apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: {{ .Values.traefik.namespace }}
spec:
  defaultCertificate:
    {{- if .Values.traefik.cloudflareTls.existingSecret }}
    secretName: {{ .Values.traefik.cloudflareTls.existingSecret }}
    {{- else }}
    secretName: cloudflare-tls
    {{- end }}
