{{- if and .Values.cleanuperr.enabled (not .Values.cleanuperr.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: cleanuperr-secret
  labels:
    app.kubernetes.io/name: cleanuperr
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
type: Opaque
data:
    QBITTORRENT__USERNAME: {{ .Values.cleanuperr.secrets.qbittorrent.username | b64enc }}
    QBITTORRENT__PASSWORD: {{ .Values.cleanuperr.secrets.qbittorrent.password | b64enc }}
    SONARR__APIKEY: {{ .Values.cleanuperr.secrets.sonarr.apiKey | b64enc }}
    RADARR__APIKEY: {{ .Values.cleanuperr.secrets.radarr.apiKey | b64enc }}
    LIDARR__APIKEY: {{ .Values.cleanuperr.secrets.lidarr.apiKey | b64enc }}
{{- end }}
