kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: patch-middleware
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: patch-middleware
  apiGroup: rbac.authorization.k8s.io
