## Default values for Cloudflared

## @section Image parameters

## @param image.repository The Docker repository to pull the image from.
## @param image.tag The image tag to use.
## @param image.imagePullPolicy The logic of image pulling.
##
image:
  repository: cloudflare/cloudflared
  tag: "2023.10.0"
  imagePullPolicy: IfNotPresent

## @section Deployment parameters

## @param replicaCount The number of replicas to deploy.
##
replicaCount: 1

## @param managed.enabled Whether to enable Managed (CF Zero Trust Dashboard) tunnel configuration. Cannot coexist with the local one.
## @param managed.token The connector token provided at the end of the CF Zero Trust tunnel creation.
## @param managed.existingSecret The name of the existing secret containing the token. The secret key must be set to 'cf-tunnel-token'.
managed:
  enabled: true
  token: ""
  existingSecret: ""

## @param local.enabled Whether to enable Local (CLI) tunnel configuration. Cannot coexist with the managed one.
## @param local.auth.tunnelID The Argo Tunnel ID you created. Check the configuration section for details.
## @param local.auth.accountTag The Argo tunnel account tag.
## @param local.auth.tunnelName The Argo tunnel name.
## @param local.auth.tunnelSecret The Argo tunnel secret.
## @param local.auth.existingSecret The name of an existing secret containing the Argo tunnel settings.
## @param local.warpRouting Whether to enable WARP traffic routing to local subnets.
## @param local.ingress The ingress settings to apply. Check the configuration section for examples.
##
local:
  enabled: false
  auth:
    tunnelID: ""
    accountTag: ""
    tunnelName: ""
    tunnelSecret: ""
    existingSecret: ""
  warpRouting: false
  ingress: []
