{{- if and .Values.local.enabled (not .Values.local.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: tunnel-secret
type: Opaque
stringData:
  tunnel-config.json: >
    {
      "AccountTag": "{{ required "The Argo Tunnel Account Tag is missing." .Values.local.auth.accountTag }}",
      "TunnelSecret": "{{ required "The Argo Tunnel Secret is missing." .Values.local.auth.tunnelSecret }}",
      "TunnelID": "{{ required "The Argo Tunnel ID is missing." .Values.local.auth.tunnelID }}",
      "TunnelName": "{{ required "The Argo Tunnel Name is missing." .Values.local.auth.tunnelName }}"
    }
{{- end }}
